# Generated by Django 4.1.5 on 2023-01-27 20:10

import cadastros.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('situacao', models.CharField(max_length=150, verbose_name='Situação')),
                ('id_sap', models.CharField(max_length=150, verbose_name='Id SAP')),
                ('id_servico', models.CharField(max_length=150, verbose_name='Id Serviço')),
                ('centro', models.CharField(max_length=150, verbose_name='Centro')),
                ('cnae', models.CharField(max_length=150, verbose_name='Cnae')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=150, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade!')),
                ('telefone', models.CharField(max_length=150, verbose_name='Telefone!')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('gestor', models.CharField(max_length=150, verbose_name='Gestor')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
                ('data_final', models.DateField()),
                ('arquivo', models.FileField(upload_to=cadastros.models.user_path)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validado_em', models.DateField(auto_now_add=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('justificativa', models.TextField(max_length=255)),
                ('comprovante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.comprovante')),
                ('validado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('siape', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campus')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('observacao', models.CharField(max_length=255, verbose_name='Observacao!')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.classe', verbose_name='Classe pretendida!')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comprovante',
            name='progressao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.progressao', verbose_name='Progressao!'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividade',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.classe'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.status'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.UniqueConstraint(fields=('nome', 'descricao'), name='unica_num_atividade_campo'),
        ),
    ]
